name: nf1-mouse
channels:
  - conda-forge
  - bioconda

dependencies:
  - biscuit
  - bwameth
  - bismark
  - bowtie2
  - samtools
  - pysam
  - fastqc
  - fastp
  - python>=3.10
  - snakemake-minimal
